"use client"

import React, { useRef } from 'react';
import { motion } from 'framer-motion';
import { Button } from './ui/button';
import { 
  Printer, 
  Download, 
  X, 
  FileText, 
  Copy, 
  Share2, 
  Calendar
} from 'lucide-react';
import { reportPreviewData } from '@/lib/dummyData';
import ReactMarkdown from 'react-markdown';
import { 
  Dialog, 
  DialogContent,
  DialogOverlay,
  DialogTitle
} from './ui/dialog';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './ui/tooltip';
import { Badge } from './ui/badge';

interface ReportPreviewProps {
  isVisible: boolean;
  onClose: () => void;
}

const ReportPreview: React.FC<ReportPreviewProps> = ({ isVisible, onClose }) => {
  const reportRef = useRef<HTMLDivElement>(null);
  
  if (!isVisible) return null;
  
  const renderMarkdown = (content: string) => {
    return <ReactMarkdown>{content}</ReactMarkdown>;
  };
  
  const currentDate = new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'America/Los_Angeles',
  }).format(new Date());
  
  const handlePrint = () => {
    const printContent = reportRef.current?.innerHTML;
    
    if (printContent) {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>${reportPreviewData.title}</title>
              <style>
                body {
                  font-family: 'Pretendard', sans-serif;
                  line-height: 1.5;
                  padding: 20px;
                  max-width: 800px;
                  margin: 0 auto;
                  color: #000;
                  background: #fff;
                }
                h1, h2, h3, h4 {
                  margin-top: 20px;
                  margin-bottom: 10px;
                  color: #000;
                }
                p {
                  margin-bottom: 10px;
                  color: #000;
                }
                table {
                  border-collapse: collapse;
                  width: 100%;
                }
                th, td {
                  border: 1px solid #ddd;
                  padding: 8px;
                }
                th {
                  background-color: #f2f2f2;
                }
                .report-header {
                  border-bottom: 2px solid #333;
                  padding-bottom: 10px;
                  margin-bottom: 20px;
                }
                .report-meta {
                  font-size: 14px;
                  color: #666;
                  margin-bottom: 10px;
                }
                .report-footer {
                  margin-top: 30px;
                  border-top: 1px solid #ddd;
                  padding-top: 10px;
                  font-size: 12px;
                  color: #666;
                }
              </style>
            </head>
            <body>
              <div class="report-header">
                <h1>${reportPreviewData.title}</h1>
                <div class="report-meta">
                  <p>Date: ${reportPreviewData.createdAt}</p>
                  <p>Author: ${reportPreviewData.author}</p>
                </div>
              </div>
              <div class="report-content">
                ${printContent}
              </div>
              <div class="report-footer">
                <p>This report was automatically generated by the 4INLAB Autonomous Factory AI System.</p>
                <p>Generated: ${currentDate}</p>
              </div>
            </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.print();
      }
    }
  };
  
  const handleDownload = () => {
    alert('PDF download function executed. (Actual download not implemented)');
  };

  const handleCopy = () => {
    alert('Report content copied to clipboard. (Actual copy not implemented)');
  };
  
  const handleShare = () => {
    alert('Report share link generated. (Actual sharing not implemented)');
  };
  
  return (
    <Dialog open={isVisible} onOpenChange={() => onClose()}>
      <DialogOverlay className="bg-black/80 backdrop-blur-sm" />
      <DialogContent className="max-w-4xl w-[95%] max-h-[90vh] p-0 border-none bg-transparent shadow-none">
        <DialogTitle className="sr-only">{reportPreviewData.title}</DialogTitle>
        <motion.div
          className="bg-card rounded-lg shadow-xl w-full h-full flex flex-col overflow-hidden"
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.9, opacity: 0 }}
        >
          <div className="sticky top-0 bg-card z-10 p-4 border-b flex justify-between items-center backdrop-blur-sm bg-opacity-80">
            <div className="flex items-center">
              <div className="bg-brand/10 p-2 rounded-md mr-3">
                <FileText className="h-5 w-5 text-brand" />
              </div>
              <div>
                <h2 className="text-xl font-bold">{reportPreviewData.title}</h2>
                <div className="flex items-center text-sm text-muted-foreground gap-3 mt-1">
                  <div className="flex items-center">
                    <Calendar className="h-3 w-3 mr-1" />
                    <span>{reportPreviewData.createdAt}</span>
                  </div>
                  <span>|</span>
                  <span>{reportPreviewData.author}</span>
                </div>
              </div>
            </div>
            
            <div className="flex items-center space-x-2">
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={handleCopy}
                      className="h-8 w-8 p-0"
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>Copy Content</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
              
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={handleShare}
                      className="h-8 w-8 p-0"
                    >
                      <Share2 className="h-4 w-4" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>Share Report</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
              
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={handlePrint}
                      className="h-8 w-8 p-0"
                    >
                      <Printer className="h-4 w-4" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>Print</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
              
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      onClick={handleDownload}
                      className="h-8 w-8 p-0"
                    >
                      <Download className="h-4 w-4" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>Save as PDF</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
              
              <Button 
                variant="ghost" 
                size="sm" 
                onClick={onClose}
                className="h-8 w-8 p-0"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
          
          <div className="flex-1 overflow-auto p-0">
            <div className="bg-white text-black px-8 py-6 min-h-full">
              <div className="max-w-4xl mx-auto">
                <Badge variant="outline" className="mb-4">Auto-Generated Report</Badge>
                <div 
                  ref={reportRef}
                  className="prose prose-sm max-w-none"
                >
                  {renderMarkdown(reportPreviewData.content)}
                </div>
              </div>
            </div>
          </div>
          
          <div className="bg-card p-3 border-t text-center text-xs text-muted-foreground">
            This report was automatically generated by the 4INLAB Autonomous Factory AI System. • {currentDate}
          </div>
        </motion.div>
      </DialogContent>
    </Dialog>
  );
};

export default ReportPreview;